default_language_version:
  python: python3.12

repos:

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]
        args: [
          "--fix", "--preview"
        ]
        exclude: "migrations"


  #      - id: pytest
#        name: pytest
#        entry: pytest
#        language: python
#        stages: [ commit ]
#        pass_filenames: false
#        always_run: true
#        args: [ "./app"]


  -   repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
      -   id: isort


  - repo: https://github.com/asottile/add-trailing-comma  # проставляет запятые
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]


  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
          --in-place,
          --remove-all-unused-imports,
          --ignore-init-module-imports,
          --remove-unused-variables,
        ]


  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          --config=.flake8,
        ]
        exclude: "migrations"
        additional_dependencies:
          - flake8-builtins>=1.5.3
          - flake8-commas>=2.0.0
          - flake8-debugger>=4.0.0
          - flake8-comprehensions>=3.3.1
          - flake8-eradicate>=1.0.0
          - dlint>=0.11.0


  -  repo: https://github.com/myint/docformatter # форматирует докстринг
     rev: v1.7.5
     hooks:
       - id: docformatter
         args: [
             --in-place,
             --blank,
         ]